#define SETBIT(WORD,BP) (WORD|=(1<<BP))^M
#define SETBYTE(WORD,BP) (WORD|=(0XFF<<BP))^M

#define CLRBIT(WORD,BP) (WORD&=~(1<<BP))^M

#define STATUSBIT(WORD,BP) ((WORD>>BP)&1)^M

#define WRITEBIT(WORD,BP,BIT) (WORD=((WORD&~(1<<BP))|(BIT<<BP)))^M

#define WRITENIBBLE(WORD,SBP,NIBBLE) (WORD=((WORD&~(0xf<<SBP))|(NIBBLE<<SBP)))^M

#define WRITEBYTE(WORD,SBP,BYTE) (WORD=((WORD&~(0xff<<SBP))|(BYTE<<SBP)))^M

#define WRITEHWORD(WORD,SBP,HWORD) (WORD=((WORD&~(0xffff<<SBP))|(HWORD<<SBP)))^M
#define SCLRBIT(WORD,SBP) (WORD=1<<SBP)^M
#define SSETBIT(WORD,SBP) (WORD=1<<SBP)^M
#define READNIBBLE(WORD,SBP) ((WORD>>SBP)&15)^M

